---
- name: Restart dhcpcd
  listen: dhcpcd
  community.general.runit:
    name: dhcpcd
    state: restarted

- name: Reload iptables
  listen: iptables
  ansible.builtin.command: /usr/local/sbin/iptables-reload
